### ISSUE TITLE
[BUG] < No module named 'Battery_Testing_Software'>

### ISSUE THREAD

**Issue by ColinBolle** [SanliFaez/FAIR-Battery#2]
**Describe the bug**
When I try to run the battery 101 test file it says: No module named 'Battery_Testing_Software' while the folder is clearly there.
I have run the setup.py and everything is correctly installed. A fellow student tried making a temporary python path but it doesn't fix things.

**To Reproduce**
1. Run the BatteryTest_View.py

**Expected behavior**
The file should run but since it cannot import everything it doesn't.

**Screenshots**

**System Information**
 - OS: Windows 10
- Python 3.8.11 as was installed via the setup.py file from the labphew gitlab

**Comment by Cinbarker** [comment]
Hi @ColinBolle, this is indeed caused by the pythonpath not being set. 
Try run this line in a terminal: 

`python -c "import sys; print(sys.path)" `

If the path was set correctly this should print the path to the Battery_Testing_Software folder. 
Note: in the above command, if ‘python’ doesn’t work, try ‘python3’

**Comment by Cinbarker** [comment]
How is it going with this issue @ColinBolle? I put a bit more to help with this issue here:
[ImportError: No module named ‘Battery_Testing_Software’](https://fair-battery.readthedocs.io/en/latest/troubleshooting.html#importerror-no-module-named-battery-testing-software)
