### ISSUE TITLE
[BUG] <dwf module missing>

### ISSUE THREAD

**Issue by Teun0204** [SanliFaez/FAIR-Battery#3]
**Describe the bug**
FileNotFoundError: Could not find module 'dwf' (or one of its dependencies). Try using the full path with constructor syntax. This is the error I get when I try to run the Battery_Test_View. I tried to uninstall dwf and reinstall it but got the same error.

**To Reproduce**
1. Go to 'examples'
2. Set pythonpath variable '....'
3. Run script 'Battery_Test_View'
4. See error 'FileNotFoundError: Could not find module 'dwf' (or one of its dependencies)'

**Expected behavior**
I expected the program to run

**Screenshots**

**System Information**
 - OS: Windows
 - OS Version Windows 10
 - Python Version [3.8.11]

**Additional context**

**Comment by Cinbarker** [comment]
Hi @Teun0204, this happens when the waveforms SDK is not installed correctly. It is a dependency of the dwf module. Did you install this? If not you can download it from here: https://mautic.digilentinc.com/waveforms-download
and then try again. Also make sure to not just install waveforms, but most importantly install the SDK. On windows this is just a matter of selecting the SDK option in the installer.

**Comment by Cinbarker** [comment]
I hope the issue has been solved! I made a more detailed post about it on the troubleshooting section of the docs:

[FileNotFoundError: Could not find module ‘dwf’ (or one of its dependencies)](https://fair-battery.readthedocs.io/en/latest/troubleshooting.html#filenotfounderror-could-not-find-module-dwf-or-one-of-its-dependencies)
